apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: app
spec:
  method: kubernetes
  mount: kubernetes
  namespace: admin
  kubernetes:
    role: role1
    serviceAccount: app
    audiences:
      - vault