apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultAuth
metadata:
  name: demo-operator
  namespace: vault-secrets-operator-system
  labels:
    cacheStorageEncryption: "true"
spec:
  method: kubernetes
  mount: demo-auth-mount
  vaultConnectionRef: default
  kubernetes:
    role: auth-role-operator
    serviceAccount: demo-operator
    audiences:
      - vault
  storageEncryption:
    mount: demo-transit
    keyName: vso-client-cache