apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: vso-db-demo-create
  namespace: demo-ns
spec:
  mount: demo-db
  path: creds/dev-postgres
  destination:
    create: true
    name: vso-db-demo-created
  rolloutRestartTargets:
  - kind: Deployment
    name: vso-db-demo
