apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: vso-db-demo
  namespace: demo-ns
spec:
  mount: demo-db
  role: dev-postgres
  destination:
    create: false
    name: vso-db-demo
  rolloutRestartTargets:
  - kind: Deployment
    name: vso-db-demo
