defaultVaultConnection:
  # toggles the deployment of the VaultAuthMethod CR
  enabled: true

  # Address of the Vault Server
  # Example: http://vault.default.svc.cluster.local:8200
  # address: "https://vault-cluster-public-vault-generated-stuff-here.z1.hashicorp.cloud:8200"
  skipTLSVerify: false